### ISSUE TITLE
Question 8 attributes appearing for all questions

### ISSUE THREAD

**Issue by Lextuga007** [CDU-data-science-team/honos#10]
Following code review the categories with question 8 column (forgot the name) with data C, T are repeated as an attribute to the patient and not just to the question 8.

I want to recode to have NAs next to all questions but 8 and have the category if that appears as an example.

**Comment by milanwiedemann** [comment]
fixed in our internal data package, will be moved here once I simulate more fake data for the i8 questions

**Comment by Lextuga007** [comment]
I'll delete the branch as I didn't work on it. 🥇
