### ISSUE TITLE
Move hardcoding to specific .rda

### ISSUE THREAD

**Issue by Lextuga007** [CDU-data-science-team/honos#29]

**Comment by ChrisBeeley** [comment]
Please not csv, I hate csv. Can we use .rda via `usethis::use_data()`?

**Comment by Lextuga007** [comment]
Yes! Any reason to use the {usethis} package too is great.

**Comment by Lextuga007** [comment]
Not sure what the original issue was related to. The file in data/ is an .rda file. Closing issue 😃
